version: "3"

services:
  bot:
    container_name: "stchb"
    restart: always
    build: .
    ports:
      - "8443:8090"
    links:
      - redis

  redis:
    image: "redis:6-alpine"
    container_name: "redis"
    restart: always
