[bot]
webhook = "{WEBHOOK}" # If the field is empty (""), the bot starts using "Polling".
token = "{TOKEN}"
port = "8090"

[database]
    [database.redis]
    addr = "redis:6379"
    password = ""
    db = 0

[chat]
queue = 10 # Maximum number of users in the queue.
users = 2 # Number of users in one chat.