[bot]
webhook = "{WEBHOOK}" # If the field is empty(""), the bot is started using "Polling".
token = "{BOT_TOKEN}"
port = "8090"

[database]
    [database.redis]
    addr = "redis:6379"
    password = ""
    db = 0

[chat]
queue = 10
users = 2